export const LOAD_SLIDES = 'LOAD_SLIDES';
export const VIEW_FULLSLIDES = 'VIEW_FULLSLIDES';
export const VIEW_SLIDESHOW = 'VIEW_SLIDESHOW';
export const CHANGE_SLIDE = 'CHANGE_SLIDE';
export const START_SLIDE = 'START_SLIDE';
export const END_SLIDE = 'END_SLIDE';

export const LOAD_PROGRESS = 'LOAD_PROGRESS';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
